### ISSUE TITLE
Rename 'visibility' to vue 

### ISSUE THREAD

**Issue by fnoop** [Yuliang-Lee/vue-visibility-change#2]
Most vue plugins or wrappers name themselves to be obviously Vue, ie:
'VueVisibility'
 instead of
'visibility'

**Comment by Yuliang-Lee** [comment]
You mean this?
https://github.com/Yuliang-Lee/vue-visibility-change/blob/master/src/index.js#L51

**Comment by fnoop** [comment]
Duh, this is default export, sorry!

Yes, this works fine:
```
import VueVisibility from 'vue-visibility-change'
Vue.use(VueVisibility)
```
